# Generated by Django 4.2.6 on 2023-10-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='product_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='items.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id',
            field=models.IntegerField(default=True),
        ),
        migrations.DeleteModel(
            name='product_item',
        ),
    ]
