# Generated by Django 4.2.6 on 2023-10-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
