# Generated by Django 4.2.6 on 2023-11-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_product_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category_id',
        ),
    ]
