# Generated by Django 4.2.6 on 2023-11-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_product_created_at_product_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_solid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product'),
        ),
    ]
