# Generated by Django 4.2.6 on 2023-11-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_brand_product_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
