# Generated by Django 4.2.6 on 2023-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_product_slug_alter_product_name_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
