# Generated by Django 4.2.6 on 2023-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
