# Generated by Django 4.2.6 on 2023-12-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.comment'),
        ),
    ]
