# Generated by Django 5.0 on 2023-12-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_comment_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
