# Generated by Django 4.2.6 on 2023-11-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0002_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
