# Generated by Django 5.0 on 2023-12-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='view_product.userinfo'),
        ),
        migrations.AddField(
            model_name='vistor',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='view_product.userinfo'),
        ),
    ]
