# Generated by Django 5.0 on 2023-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_product', '0002_useraction_user_info_vistor_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='referrer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
